- hosts: nginx-setup
  become: true
  tasks:
  - name: "Install Nginx"
    apt:
      name: nginx
      state: latest
      update_cache: true
- hosts: docker-setup
  become: true
  tasks:
  - name: "Install pip"
    apt:
      name: python3-pip
      state: latest
      update_cache: true
  - name: "Install Docker"
    pip:
      name: docker
